### ISSUE TITLE
Add cc, py and java builtins

### ISSUE THREAD

**Issue by cameron-martin** [cameron-martin/bazel-lsp#12]
#8 added some builtins, but this proto does not include things like `cc_library`. I'm not sure where these are meant to come from.

**Comment by daivinhtran** [comment]
I think `cc_library` is now migrated to Starlark?

**Comment by daivinhtran** [comment]
The cc rules come from https://github.com/bazelbuild/rules_cc (Starlark implementation of cc rules). I believe if we can resolve `http_archive` and/or `local_repository` declaring `@rules_cc`, it should work.

**Comment by cameron-martin** [comment]
That repo still just calls builtins. I _think_ they might be written in starlark now but in the bazel repo.

See https://github.com/bazelbuild/rules_cc/blob/51b77439a109b8c8f75ad70a130293291ed8b851/cc/defs.bzl#L49

**Comment by cameron-martin** [comment]
Builtins such as `toolchain`, `toolchain_type` and `package` also aren't included in this protobuf.

**Comment by cameron-martin** [comment]
Looks like we can use `bazel info build-language` here. See https://github.com/bazelbuild/vscode-bazel/issues/1#issuecomment-1993870458
