### ISSUE TITLE
Unnecessary warning in WORKSPACE files: A `load` statement not at the top of the file

### ISSUE THREAD

**Issue by hauserx** [cameron-martin/bazel-lsp#54]
Load statements should be at top of regular .bzl files, but it's customary to have load statements across whole WORKSPACE file. 

It's somewhat lower priority as the WORKSPACE file is being replaced by MODULE file, but still is used in multiple projects.

**Comment by cameron-martin** [comment]
This seems to be an issue with starlark-rust, where it unconditionally triggers that lint: https://github.com/facebook/starlark-rust/blob/decc502ae4a293b68e056b76acaf12033897b835/starlark/src/analysis/flow.rs#L324

I think it would require an addition to [`Dialect`](https://github.com/facebook/starlark-rust/blob/decc502ae4a293b68e056b76acaf12033897b835/starlark_syntax/src/dialect.rs#L36). I'll open an issue on starlark-rust.

**Comment by cameron-martin** [comment]
https://github.com/facebook/starlark-rust/issues/135

**Comment by hauserx** [comment]
Other solution would be for `bazel-lsp` to filter out `misplaced-load` lints for `WORKSPACE` files, this way no change to starlark-rust would be necessary. Later I will create a PR with this change.

Also noted a few other common warnings when checking a few repos (like rust_go/cc/rust), let me create a list of it, maybe worth adding some support for all at once if necessary. 

As a side note, possibly would be worth creating `bazel-lsp lint` command to run those lints in more programmatic way.
